### ISSUE TITLE
Load openings from filesystem

### ISSUE THREAD

**Issue by MaSchwarz** [Clariity/ChessOpenings#13]
**Is your feature request related to a problem? Please describe.**
Using a firebase connection to manage a bunch of static openings seams pretty over engineered to me.
An additional downside is that contributers need a firebase account.

**Describe the solution you'd like**
Openings could be stored in a simple JSON file.
There are already premade JSON files with a bunch of openings (e.g. https://github.com/hayatbiralem/eco.json/blob/master/eco.json)

**Describe alternatives you've considered**
Using other local storages (e.g. SQLite) could be a solution, but it would require an additional client to read and write and has no advantages compared to a simple JSON file.

**Comment by Clariity** [comment]
ChessOpenings 2.0 includes a major overhaul with user accounts and userdata for statistics and achievements. Users will require a ChessOpenings account in order to submit openings  (in order to prevent spam), as well as attribute openings to users.

Firebase is core to content delivery with the app and will remain that way
